### PR TITLE
[WIP] Fxsystem

### PR DESCRIPTION
**Pull request by nemerle**
Not finished, not working, ... just not. :)
    
DONE:
- Implemented ECS'like FXSystem
- FXSystem has minimal logic for handling effect state 'evolution'
- NetFx creation from an Effect
- HandleBasedStorage knows how to convert iterator to a storage handle.
- added commented out ReferenceCounting wrapper for a Handle.
- GameDataStore knows how to return FxInfo * based on an effect name.
- IndexedStringPacker::addString returns the id of the added string
- Use slightly more descriptive enums for FX related flags
- a small fix for potential crash when target_idx does not map to a correct entity in process_replacement_strings
    
TODO:
- expose relevant FXSystem namespace members to LUA
- hide NetFx functions from LUA
- generate NetFx from active FXSystem entries,?attach based on visibility/distance?,
- LUA api documentation

### CODE REVIEW

**Comment by broxen** [comment]
Aside from resolving merge conflicts, any reason this can't merge?

**Comment by nemerle** [comment]
Test review message, testing

**Comment by nemerle** [comment]
ping

**Comment by nemerle** [comment]
ping2

**Comment by nemerle** [comment]
merged from another PR

**Pull request closed without merging**
