### PR TITLE
[WIP] Introducing NetFxHelpers

### PR DESCRIPTION
**Pull request by nemerle**
To use the NetFx

1. Create the effect:
`auto handle = createNetFx("FX/WORLD/CITY/STREETSTEAM01.FX");`
2. Set the source location for the effect
`setSourceLocation(handle,{0,0,0});`
`setSourceEntityAndBone(handle,entity_idx,bone_id)`
3. Set the target of the effect
`setTargetLocation(handle,{0,10,0});`
4. Apply some other magics to NetFx:
`NetFx &(lookup(handle));`
5. Attach the effect to an entity:
`attachToEntity(entity_ptr,h);`

Notes:

* The effects lifetime (destruction/changes) is not managed: that's the job of the FxSystem, which does not exist yet.
* In the future, additional helpers will be created.

Todo:

* Register the NetFxHelpers functions for lua access.

### CODE REVIEW

**Comment by HeraldOfOmega** [comment]
I remember Flurry continuing its effects and animation after the first blow of it defeated an enemy.

**Comment by broxen** [comment]
Pending a working Lua script. This is ready for merge.

**Comment by cyanpill** [comment]
Based on what ZopharShinta found to work, I added this code to findAttrib in datahelpers:

> if (powtpl.AttackFX != "")
>      {
>         QString fxName = QString("FX/" + powtpl.AttackFX);
>         NetFxHandle locFx = createNetFx(fxName);
>         setSourceLocation(locFx, ent.m_entity_data.m_pos);
>         setTargetLocation(locFx, target_ent->m_entity_data.m_pos);
>         GameDataStore &data(getGameData());
>         NetFxHandle fx = createNetFx(fxName);
>         setSourceEntityAndBone(fx, ent.m_idx, 4); // 4 for head
>         attachToEntity(fx, &ent);
>     }

And it works! the only problem is the target location is always off in the world somewheres. I tried every other glm::vec3 I could find for the target, but nothing changed the direction of the projectile.

**Comment by nemerle** [comment]
TODO: add verification of NetFx in attachToEntity to prevent sending client crashing NetFxs

**Comment by nemerle** [comment]
Another, cleaner PR is comming

**Pull request closed without merging**
