### PR TITLE
Initial work on map transfers. WIP

### LINKED ISSUE #527: Implement Map Transfers
## Summary
We need to implement MapTransfers (client calls these MapXfers)

Currently we can load multiple maps (by manually changing player maps in the DB). Plus, we have the `/mapmenu` command, which brings up the mapxfer window (MapXferList), but it's not populated with anything, so does nothing.

To complete this Issue, the following features should be implemented:
### Features to Completion
- [ ] Implement MapTransfers (svr->client pkt 11)
- [ ] Implement MapTransferWait (svr->client pkt 10)
- [ ] Implement `/mapmove {idx}` command so we can actually move =)
- [ ] Instigate MapXfer when zoning through tunnels or hazard doors in the war walls

### Bonus Features
- Populate MapXferList with a list of major zones, and figure out how to make clicking on those zone names fire a MapXfer.
- Door Animation Start (client->svr pkt 52)
- Door Animation Exit (client->svr pkt 53)
- Populate Monorail destination window by marrying `MapInstance::on_enter_door()`, MapXferList, and `MapInstance::on_location_visited` to display MapXferList when you're near the monorail door.
- Fill additional information from maps.bin #475

### PR DESCRIPTION
**Pull request by Magentah**
Closes #527 .

Additions/Modifications:

- Added all map zones to the /mapmenu command.
- Links clicked in the /mapmenu command will now transfer you to that the map clicked.
- /movezone {map_idx} and /mz {map_idx} have been added, and will transfer you to the map index specified.

How:

- Events added for server->client opcodes 10 (MapXferWait) to tell the client which map to show the loading screen and prepare, and 11 (MapXferRequest) to tell the client which map server ip and port to connect to.

- Events added for client->server opcodes 11 (InitiateMapXfer) to tell the server that the loading screen is shown and to request the map server to connect to and 12 (MapXferComplete) to tell the server that it has connected to the new map server.

- Added ClientMapXferMessage event, used to tell the map server that a map transfer is happening for a client session.

- Added a std::map and associated functions to the map server to allow checks and updates for the client map transfers in progress

- Updated the ClientRenderingResumed to check if a map transfer is in progress before sending the motd.

- Added ExpectClientMapResponse event handler to map instances, used to notify when the instance is ready to receive a client for a map transfer

- Updated on_enter_door to handle map transfers (currently used by the mapmenu)

- Added game_server_id to MapSessionClient to allow sending ClientMapXferMessage to the map server from SlashCommands.

### CODE REVIEW

**Comment by broxen** [comment]
Please resolve merge conflicts when you get a chance. Thank you!

**Comment by Magentah** [comment]
Conflicts resolved. Also updated some things re: #552 comments from @nemerle

**Comment by broxen** [comment]
Clicking on a door in Outbreak crashes the server:
```
[log.mapevents]Debug   : "Adding session 1 to the map requests"
[log.mapevents]Debug   : "Adding client transfer map index for client session 1 to map index 0"
[log.mapevents]Debug   : Map Transfer Initiated with token 1
Debug   : Existing client session reused
Warning : Create_cookie still needs a good algorithm. 0xa00a498
Debugging has finished
```

**Comment by broxen** [comment]
Also, I recommend we clean up some of the debug output, as anyone running a server with multiple users transferring maps is going to make server output unreadable.

As a part of this, I would move all of the map transfer debug output to a new logging category `logMapXfers` or something.

**Comment by broxen** [comment]
Maybe instead of spawning at 0,0,0 for each map, we spawn at a random door exit? That would work for maps that do not have a player_spawn. Thoughts?

**Comment by Magentah** [comment]
There are no spawn locations loaded at this point. The logic is there, mostly, but the array of spawns is always empty. I'm working on adding those in the other branch with zone boundaries/mapswap markers.

**Comment by Magentah** [comment]
I also have a feeling that the doors are broken because they don't actually send the correct values when clicking - they always send "name" as 0. I don't think this can be solved until either we know what map the door is intended to transfer to (which means knowing mapswap markers, in the other branch) or the door sends the correct map data.

**Pull request merged**
