### PR TITLE
Added default keybinds

### PR DESCRIPTION
**Pull request by broxen**
Step 1 of #131  .

Additions/modifications proposed in this pull request:
- Added default keybinds to Character.cpp
- Modified degrees_for_turns in sendOptionsFull()
- Modified the map instance data load message to make it more clear
- Tested: it works! For `q` and `e` at least. I haven't tested every button.

### CODE REVIEW

**Comment by nemerle** [comment]
The code looks good, although the mod-keys are not the ones you've guessed, they look like this:
```cpp
enum ModKeys
{
    NO_MOD = 0,
    CTRL_MOD = 0x1,
    SHIFT_MOD = 0x2,
    ALT_MOD = 0x3,
};
```

**Comment by broxen** [comment]
Oh. Cool. Thanks Nem!

I'm not familiar with best practices, but should I move the enums to the header file?

**Comment by broxen** [comment]
Also, I wasn't sure if bind[114] was correct. Is there any other definition for mouse chords?

**Comment by nemerle** [comment]
1. Enums should be in a header file, if any other piece of code want's to use them, otherwise putting them in an anonymous namespace inside the cpp file should be preferred. 
2. I do not believe that I0 client handles those mouse chords as a part of keybindings.

Also default keybinds can be read from bin/kb.bin, so we could store keybinds in a MapServerData and read them on startup ?
I'm going to add serializer for the kb.bin just in case :)

**Comment by broxen** [comment]
> Also default keybinds can be read from bin/kb.bin, so we could store keybinds in a MapServerData and read them on startup ?

This is preferable. From there we could override any user set keybinds from the dbase. This would reduce the clutter in the dbase and here in Character.cpp.

In light of that, I'll push these changes and open a new issue to follow up?

**Comment by nemerle** [comment]
Agreed, I should be able to push the serialization code today, depends on how the cold, I've somehow acquired, allows :sneezing_face:

**Comment by broxen** [comment]
Feel better!

Conferences will do that to you. Too many new germs around.

**Comment by broxen** [comment]
This is ready for commit. Thanks Nem. Feel better brotha.

**Pull request merged**
