### PR TITLE
Updated database schemas and cleaned up data folder

### PR DESCRIPTION
**Pull request by broxen**
Updated database schemas based upon #133, added database schema exports to the Data folder

Addresses #133

Additions/modifications proposed in this pull request:
- Updated `segs` and `segs_game` database schemas per #133
- Added schema exports to the Data folder as backup
- Proposed: delete other SQL scripts in the `./Projects/CoX/Data/` folder, as they are no longer relevant.

### CODE REVIEW

**Comment by nemerle** [comment]
The old sql scripts were targeting pgsql, but I agree that only storing sqlite is good enough for now.
On day, when we add a capability of creating/initializing databases from the db tool, then we can start worrying about the specific DB server specific scripts.

**Comment by broxen** [comment]
Ah I see. I can try to import the schema into dbdesigner.net as pgsql and export scripts for that. My only recommendation then, would be to add a subfolder to data for pgsql, so it's clear to users what is what.

**Comment by nemerle** [comment]
That would be great, thank you !

**Comment by broxen** [comment]
Leaving myself a note to test this tool out: https://github.com/dimitri/pgloader

**Comment by broxen** [comment]
I've been on Chromebook all weekend, so I haven't been able to test this, but assuming it imports correctly, this should be ready to go.

I can test late tonight and give the OK, but would love any feedback. Thank you in advance!

**Comment by broxen** [comment]
After some small tweaks, I'm showing successful tests with both sqlite and pgsql.

Unless you find something different, this is OK to commit.

**Pull request merged**
