### PR TITLE
Big blob of changes

### PR DESCRIPTION
**Pull request by nemerle**

### CODE REVIEW

**Comment by nemerle** [comment]
@broxen when You have some time, please test this commit, it fixes/implements some much needed functionality ( client logout handling, PYR<->Quaternion conversion routines, logging filtering )

**Comment by broxen** [comment]
Awesome! I'll jump on this over the weekend.

**Comment by broxen** [comment]
Some testing on Fedora 26:

**Summary:**
Logging in with two clients, same user `segs`, different characters `StrongDude` and `WeakDude`

**Resolved**
- Issue #93 Appears resolved
- Issue #66 Tested new chat commands, along with intentional typos. Chat worked as designed! yay!
- Issue with log output appears to be resolved (see below)

**Open**
- Issue #30 Server crashed after logout with StrongDude, see console output below
- Logged out entities still appear in the world. (Seen in the moments before server crash)
- Issue #81 Ran around with StrongDude to test updates sent to other clients. Still experiencing errors with collision and position updating (rubberbanding and "jumping")
- Issue #94 Entities still aren't updating rotation to reflect character direction. Other entities remain facing one direction.
- Issue #85 is still active. Ctrl-C causes seg-fault
- Issue #71 is still active. Client times out during log character creation.
- Issue #95 is still active. Still able to log in to the same account twice

**New Issue**
- Issue #130 `Unhandled command event type 62` and `Debug   : Not all bits were consumed` which may be related (they appear together)

**ToDo:**
- Issue #63 - Need to further test on Windows (which I'll do later tonight and make a second post)

**Outputs and Logs**
From Console. Output.log and Crash.log attached.
[crash.log](https://github.com/Segs/Segs/files/1445051/crash.log)
[output.log](https://github.com/Segs/Segs/files/1445052/output.log)
```
$ ./authserver
Super Entity Game Server
http://segs.sf.net/
Copyright (c) 2006-2017 Super Entity Game Server Team (see Authors.txt)
This software is licensed! (See License.txt for details)

segs v0.4.0 alpha (The Real Beginning)
main
Debug   : Config file is missing 'location_addr' entry, will try to use default
Debug   : Config file is missing 'auth_pass' entry, will try to use default
Warning : Reading map data from ./data/bin/ folder
Debug   : Reading ./data/bin/costume.bin ... OK
Debug   : Reading ./data/bin/supergroupColors.bin ... OK
Debug   : Loading origins:
Debug   : Reading ./data/bin/origins.bin ... OK
Debug   : Reading ./data/bin/villain_origins.bin ... OK
Debug   : Loading classes:
Debug   : Reading ./data/bin/classes.bin ... OK
Debug   : Reading ./data/bin/villain_classes.bin ... OK
Warning :  All map data read
Warning :  Postprocessing runtime data ..  Hashes filled
(11453|140062135965440) Crypto seed 00000001
(11453|140062127572736) User segs trying to login from 10.0.0.22.
		id : 64u
		 : succeeded
(11453|140062135965440) Client requesting server list
(11453|140062127572736) Client selected server 1!
(11453|140062119180032) create_cookie still needs a good algorithm.0x00000002
CLIENT VERSION 4
CharacterClient id: 2
CharacterClient slots: 8
(11453|140062147495680) Connection closed
 Telling map server to expect a client with character StrongDude,0
(11453|140061903419136) create_cookie still needs a good algorithm.0x0a00c007
1 - 0 - 1
	Sending create entity
	Sending create entity
Received cookie confirm a00c009 - 1
	Sending create entity
	Sending create entity
	Sending create entity
Received window state 11 - 4
// ...
Received window state 34 - 4
Debug   : MiniMapState tile  251  for player 0x7f62a00029b0
// ...
Debug   : MiniMapState tile  272  for player 0x7f62a00029b0
Received window state 0 - 2
// ...
Received window state 24 - 4
Debug   : MiniMapState tile  251  for player 0x7f62a00029b0
// ...
Debug   : MiniMapState tile  252  for player 0x7f62a00029b0
Debug   : MiniMapState tile  251  for player 0x7f62a00029b0
Received window state 18 - 4
// ...
Received window state 4 - 2
Console command received b test
Received window state 4 - 1
Received window state 4 - 2
Console command received broadcast test
Received window state 4 - 1
Received window state 4 - 2
Console command received broad test
Received window state 4 - 1
Received window state 4 - 2
Console command received l test
Received window state 4 - 1
Received window state 4 - 2
Console command received local test
Received window state 4 - 1
Received window state 4 - 2
Received window state 4 - 1
Received window state 4 - 2
Console command received loca test
Received window state 4 - 1
Received window state 4 - 2
Console command received localy test
Received window state 4 - 1
Received window state 4 - 2
Console command received broadcaster test
pressed
pressed
Debug   : MiniMapState tile  251  for player 0x7f62a00029b0
pressed
pressed
Received window state 7 - 2
Unhandled command event type 67
Debug   : Not all bits were consumed
(11453|140062135965440) Crypto seed 00000001
(11453|140062127572736) User segs trying to login from 10.0.0.22.
		id : 64u
		 : succeeded
(11453|140062135965440) Client requesting server list
(11453|140062127572736) Client selected server 1!
(11453|140062119180032) create_cookie still needs a good algorithm.0x00000002
CLIENT VERSION 4
CharacterClient id: 2
CharacterClient slots: 8
(11453|140062147495680) Connection closed
 Telling map server to expect a client with character WeakDude,1
(11453|140061903419136) create_cookie still needs a good algorithm.0x0a00b3fe
1 - 0 - 1
	Sending create entity
	Sending create entity
	Sending create entity
	Sending create entity
	Sending create entity
Received cookie confirm a00b400 - 1
	Sending create entity
	Sending create entity
	Sending create entity
	Sending create entity
Received window state 11 - 4
// ...
Received window state 34 - 4
Debug   : MiniMapState tile  251  for player 0x7f62a0008cf0
// ...
Debug   : MiniMapState tile  272  for player 0x7f62a0008cf0
Received window state 0 - 2
// ...
Received window state 24 - 4
Debug   : MiniMapState tile  251  for player 0x7f62a0008cf0
// ...
Debug   : MiniMapState tile  251  for player 0x7f62a0008cf0
Received window state 18 - 4
Received window state 17 - 4
Received window state 16 - 4
Received window state 8 - 4
pressed
pressed
pressed
pressed
pressed
Debug   : MiniMapState tile  252  for player 0x7f62a00029b0
Debug   : MiniMapState tile  252  for player 0x7f62a00029b0
Debug   : MiniMapState tile  252  for player 0x7f62a00029b0
pressed
pressed
pressed
pressed
Received window state 4 - 1
Received window state 4 - 2
Console command received b test
Received window state 4 - 1
Received window state 4 - 2
Console command received l test
Received window state 20 - 4
Received window state 20 - 4
Received window state 20 - 4
Received window state 7 - 2
Received window state 20 - 4
Received window state 20 - 4
Received window state 20 - 4
Debug   : Unresponsive link
// ... there's probably about 30 of these
Debug   : Unresponsive link
Segmentation fault (core dumped)
```

**Comment by broxen** [comment]
@nemerle Testing on Windows 10:

**Summary**
Same setup. Two characters, same account, logged in simultaneously.

Same results all around. One notable difference in the output logs, which have some kind of formatting issue. Also there was no crash log when the server crashed after log out.
[output.log](https://github.com/Segs/Segs/files/1445135/output.log)
_no crash.log available_

One thing I noticed: Logging in with two separate accounts and logging out appears to work as intended. It's really when logging out with a character when BOTH clients are logged into the SAME account. This will be resolved by fixing #95.

Some screenshots
screenshot 51
screenshot 54
screenshot 55

**Pull request merged**
