### PR TITLE
Updated motd.smlx for 0.5.0 release.

### LINKED ISSUE #387: Update MOTD.smlx prior to v0.5.0 release
We need to update MOTD.smlx prior to v0.5.0 release. A contributor may have to wait until closer to our final release to complete this task.

It can be found here: https://github.com/Segs/Segs/blob/master/Projects/CoX/Data/scripts/motd.smlx

### Requirements
- File must be in proper CoH simple html format https://github.com/Segs/Segs/wiki/COH-Markup-Language
- Should list a few of the most interesting new features or bug fixes since last release
- Provide links for bug reporting and accessing our GitHub
- Show a few common slash commands such as `/cmdlist`
- Not exceed 40 lines as it will spill off the bottom of the screen for players with lower resolution displays.

NOTE: no real programming experience is needed here, this is just doc editing.

### PR DESCRIPTION
**Pull request by broxen**
Closes #387 

Additions/modifications proposed in this pull request:
- Updated `motd.smlx` with update summary for user-facing info.

### CODE REVIEW

**Comment by mobbyg** [comment]
Looks good to me. Maybe Nem will have something else to add. He’s going to be doing the web version soon so I can incorporate it it to the release tomorrow.

**Comment by nemerle** [comment]
Well, I'm going to 'tag' the 0.5.0 release here on github, and start preparing the archive. No idea where that 'web' thing came from mobby :P
@broxen : this looks good

**Comment by broxen** [comment]
Sounds good. Let's roll with it

**Comment by mobbyg** [comment]
Oh. That’s how it is. 

Gotta edit something so we can send users to a page for more info.  140 characters is kinda limiting. LOL

**Comment by mobbyg** [comment]
Plus I thought we were talking about the web page too. LOL

**Pull request merged**
