### PR TITLE
Updated Style Guide, & CONTRIBUTING, README with new links

### LINKED ISSUE #177: [question] Variable naming convention?
Is there a naming convention you prefer for variables?

I've been following your lead with member variables prefixed by `m_` but are there any other conventions we should follow?

I'll add whatever is defined here to the CONTRIBUTING.md and style guide.

### PR DESCRIPTION
**Pull request by broxen**
Closes #177 .

Additions/modifications proposed in this pull request:
- Renamed `CodingStyle.txt.md` to `CODING_STYLE.md`
- Updated CODING_STYLE.md and CONTRIBUTING.md with coding information.
- Updated README, CONTRIBUTING.md with new links for contributing and license.
- Removed Readme.txt in docs subfolder
- Removed License.txt in docs subfolder
- TODO: Should we just remove CODING_STYLE.md altogether? I left it as it's name is catchy enough to draw potential programmers in. Plus, now it provides a link to CONTRIBUTING.md

### CODE REVIEW

**Comment by nemerle** [comment]
Looking good, let me know when it's ready for a merge

**Comment by broxen** [comment]
This is ready, what are your thoughts on this:

TODO: Should we just remove CODING_STYLE.md altogether? I left it as it's name is catchy enough to draw potential programmers in. Plus, now it provides a link to CONTRIBUTING.md

**Comment by broxen** [comment]
Also do you prefer that I squash commits like this? Or is it better to have the history?

**Comment by nemerle** [comment]
I usually `squash` when there are a lot of micro-commits

As for CODING_STYLE, i have no preference, remove it if You want, what matters is it's contents anyway :smile:

**Comment by broxen** [comment]
This is ready for merge.

Since I've already submitted the PR, I can't squash anymore on my end, but according to the interwebs you should have an option to squash when you accept the changes and merge.

Thanks Nem!

**Pull request merged**
