### PR TITLE
Fixed issue with broadcast channel not working

### PR DESCRIPTION
**Pull request by broxen**
Removed superfluous space from check for chat commands. Fixes error with `/b` not working

Addresses #66

### CODE REVIEW

**Comment by nemerle** [comment]
Does this mean that incoming chat messages are formatted as "/bMESSAGE_TEXT" ?

**Comment by nemerle** [comment]
You could always set a break-point at ChatMessage::eChatTypes getKindOfChatMessag and see what's coming from the client

**Comment by broxen** [comment]
Shouldn't have any impact on the output, as I'm only modifying the string used for lookup in the check for chat type?

I'll confirm tonight, and will add some debug tests.

**Comment by nemerle** [comment]
Well, the change You're proposing would make getKindOfChatMessage return true for every command starting with letter "l"

**Comment by broxen** [comment]
Ah, yes. I completely missed that.

**Comment by broxen** [comment]
I've resolved any errors with Malformed chat commands, added range to local chat (100.0f for now?), fixed the broadcast chat issues, and made local_chat the fallback for any unknown scripts or commands (as in original servers). I did leave a bit of commented out debugging code for testing purposes. Please test and let me know what you think, but overall I think I tested for everything.

**Comment by broxen** [comment]
Oh, I also added some code for pulling current map from the database on the char-select screen. This is probably what I'll try to tackle next.

**Comment by nemerle** [comment]
Ok, writing a simple "hello" on the local chat window results in the client sending
"l hello\n"
and using "/local hi"
"local hi"
Both methods seem to work correctly as-is, could you give me an example that fails ?

**Comment by nemerle** [comment]
But You were right, getKindOfChatMessage should only ever chack first character since it's extracted from the start of message until first ' ' character, sorry my bad

**Pull request merged**
