### PR TITLE
Issue #388 - Catch Cereal Exceptions

### PR DESCRIPTION
**Pull request by eos428**
Issue #388 - Catch Cereal Exceptions

Every serialize functions in affected files now have try/catch blocks.
1 catch specifically for cereal::RapidJSONException (Gives out qWarning)
1 catch for std::exception (Gives out qCritical)

Additions/modifications proposed in this pull request:
- Put some unique message in each file's qWarnings and qCriticals?

### CODE REVIEW

**Comment by nemerle** [comment]
This looks great, one comment though, since all those `static void serialize` functions cannot be called from outside, please move try/catch blocks to their callers that 'are' accessible from outside ( the ones that call the 'root' serialize method), this way will reduce the number of try/catch code, and will log the error for the whole serialization attempt, and not for each failed 'step' of serialization

**Comment by eos428** [comment]
Sorry, not quite sure what you mean. Are you talking about things like serializeTo/From in places like Character.cpp and Costumer.cpp?

**Comment by nemerle** [comment]
Exactly, this way you're guarding the gates, and not every step of the way after. Since exceptions are propagated to callers,, 'guarding the gate' will work well enough :)

**Comment by nemerle** [comment]
serialization_common.h  seem like a good central point of doing this, no ? :)

**Comment by nemerle** [comment]
Looking good :)
Should I merge, or do you want to add anything in here ?

**Comment by eos428** [comment]
Ready for merging now if you wish :). Something to note though, while commonSaveTo is called quite often, every serializer seems to have their own version(s) of loadFrom. I guess that may be something to do for the future?

**Comment by nemerle** [comment]
I think all of the loadFrom functions are loading the original bin files, and that code should not throw anything :)

**Pull request merged**
