### PR TITLE
[WIP] bring the client patch up to date

### PR DESCRIPTION
**Pull request by nemerle**
moving local changes to repository

### CODE REVIEW

**Comment by dracc** [comment]
OMG it's happening! :smile:

**Comment by mobbyg** [comment]
I thought this was abandoned? LOL

**Comment by dracc** [comment]
Are there any builds of this available?
I have a version of it from a month or so ago which gives me "Failed to create OpenGL rendering context." and then it exits. No further output given when run from a terminal. All this when started through wine, as I don't use Windows.

**Comment by dracc** [comment]
Okay, so, currently this sits at 12000+ added lines. Something tells me not many will proof-read this before it gets merged. :sweat_smile:
Looking forward to testing it tomorrow though!

**Comment by nemerle** [comment]
I expect we will work on it some more before considering a merge anyway

**Comment by dracc** [comment]
I fetched your branch, get an error about a missing TextureGenerator.h when running cmake for the client. Any ideas?

**Comment by broxen** [comment]
I don't have an Intel card. How can I help test and merge this patch?

**Comment by broxen** [comment]
I think we should resolve merge conflicts here and merge this in. This is significant progress toward support for other cards, and by merging this in we can establish a foundation in the code base if someone new comes along looking to help complete/bug test.

Thoughts?

**Pull request merged**
