### PR TITLE
Alternative to Death-By-Zoning

### PR DESCRIPTION
**Pull request by HeraldOfOmega**
Additions/modifications proposed in this pull request:
Super Duper Awesome Mighty Infinite Alternative to Death-By-Zoning.

untitled5

### CODE REVIEW

**Comment by broxen** [comment]
Will pull down to test and review this weekend. Thank you @HeraldOfOmega!

**Comment by broxen** [comment]
We can actually fix this issue entirely by calling `ent->m_char->finalizeLevel();` inside of `on_expect_client()` in MapInstance. I would add it on line 725, directly beneath `toActualCharacter(...)`

If you effect that change, you can remove your changes to Character::Character(), and I'll go ahead and merge. Otherwise I'll push my own fix later this weekend (Sunday probably)

Great PR Herald! I really appreciate you looking at this!

**Comment by cyanpill** [comment]
Broxen, surely that should be finalizeCombatLevel? The hp affecting lines were moved since it depends on combat level.

**Comment by broxen** [comment]
I dunno, maybe... I thought to call finalizeLevel because it will do both that and correct any other potential issues with the Character loading. But maybe I'm being overly cautious?

**Pull request merged**
