### PR TITLE
Segsadmin uitidyup

### PR DESCRIPTION
**Pull request by miles200**
Adds to #413  .

Additions/modifications proposed in this pull request:

- Add player fade-in to settings.cfg creation, edit and save
- Start and Stop server buttons now a single dual function button
- Settings and logging (settings.cfg) now in it's own class and dialog
- General UI overhaul
- Slight change in logic when opening Settings dialog... Before only read from settings.cfg on application start up but will now read on startup and also every time settings dialog is opened, to cover any scenario
where the settings.cfg file is changed whilst SEGSAdmin is running. Removed redundant check for settings.cfg file on each save of settings, only need to check on application startup and was generating un-needed console output

### CODE REVIEW

**Comment by miles200** [comment]
Something's gone a bit weird with my git branch, it seems to have included the changes from my previous PR, not that it matters I don't think?

**Comment by broxen** [comment]
Should be fine because those changes were merged against Master.

It *could* create issues in the future, if something had changed, or your PR had been merged with conflicts, or something. So it's best to ensure that new branches are created from a clean copy of upstream/master.

I'll pull this down to test.

**Comment by broxen** [comment]
This works great!

But I have a lot of visual feedback.

### Line breaks:
line-breaks

### Console Output
console-output

### Settings Window
settings

**Comment by miles200** [comment]
UI changes in progress, currently fixed locally:

- Auto populate IP's button moved to bottom left of settings dialog
- Font changed to deja vu sans condensed in both output textedits, slightly widened UI, hopefully fixes issue with text wrapping
- Segs logo larger

Outstanding: 

- Line breaks in auth server output, seems to be some weird Qt behavior, not sure if we can leave this as is for now? 
- Outlines of certain input fields not showing on Fedora dark theme

(Think that covers all your feedback @broxen 😄 )

**Comment by broxen** [comment]
Mobby offered to test this on OSX, but barring any feedback from him, this is ready for merge.

**Comment by miles200** [comment]
Thanks @broxen I’ll tidy up /  squash my commits this afternoon

**Comment by mobbyg** [comment]
I don’t know how to pull miles’ code down to test it. Do I add his as a new project in QT?

**Comment by miles200** [comment]
@mobbyg If I'm testing on linux I create a new Qt project and clone from my fork / branch directly but not sure if there's an easier way!

**Comment by miles200** [comment]
@broxen This should be ready for merge now, if all reviewers happy. I've updated the PR description and squashed the commits.

**Pull request merged**
