### PR TITLE
auth: Don't assert on bad reconnection attempts

### LINKED ISSUE #619: Server crash on incorrect auth procedure
### Expected behavior
The server should tell the connecting client that something went wrong and go on with the day.
### Actual behavior/symptoms
https://github.com/Segs/Segs/blob/915f9096beec4de621a20ad24d6869a9b57a74a2/Projects/CoX/Common/AuthProtocol/AuthEvents.h#L69 is hit and server shuts down.
### Steps to reproduce behavior/symptoms
I'm not totally sure, but I get this assertion several times per day.
### SEGS version
develop HEAD (915f909)

### PR DESCRIPTION
**Pull request by dracc**
Closes #619 .

Additions/modifications proposed in this pull request:
- Replace `assert(op==3)` with a conditional warning message.

### CODE REVIEW

**Comment by broxen** [comment]
We need further testing on this issue. I've made this same change locally and it has resolved any crashing (and client still reconnects fine)

But per my conversation with Nem on Discord, there may be an underlying issue here with our order of operations for disconnects. @dracc is running this live on his public server (which is where we've seen this error most) so I'm hoping we can cull some real world testing data to ensure there are no unforeseen consequences here.

**Comment by broxen** [comment]
Any new results from this in testing?

**Comment by dracc** [comment]
I haven't had many connections at all lately as a configuration failure shut down my server without it shutting down and the message was outside of my screen line count. :slight_frown:

**Comment by broxen** [comment]
Moving to v7

**Comment by broxen** [comment]
This has fired twice for me when testing various things locally. While it's probably not a true "solution" it does prevent the hard crash and outputs a nice warning message for server admins.

I'm merging this for now, and we'll try to address the underlying problem in v7.

**Pull request merged**
